create extension if not exists pgcrypto;

create type public.user_role as enum ('user', 'admin');
create type public.telegram_classification as enum ('secret', 'normal');
create type public.telegram_priority as enum ('slow', 'normal', 'urgent');
create type public.telegram_category as enum ('criminal', 'administrative', 'traffic', 'security', 'tactical');
create type public.telegram_status as enum ('pending', 'in_progress', 'resolved', 'archived');
create type public.number_system as enum ('latin', 'arabic', 'hindi');

create table public.users (
  id integer generated by default as identity primary key,
  "authUserId" uuid not null unique references auth.users(id) on delete restrict,
  name text,
  "badgeNumber" varchar(80),
  email varchar(320),
  "loginMethod" varchar(64),
  role public.user_role not null default 'user',
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  "lastSignedIn" timestamptz not null default now()
);

create table public.department_settings (
  id integer generated by default as identity primary key,
  "configKey" varchar(32) not null unique default 'primary',
  "departmentName" varchar(255) not null default 'إدارة الشرطة',
  "unitName" varchar(255) not null default 'وحدة العمليات',
  "unitChiefRank" varchar(120) not null default 'العقيد',
  "unitChiefName" varchar(255) not null default 'رئيس الوحدة',
  "serialPrefix" varchar(24) not null default 'POL',
  "serialStart" integer not null default 1 check ("serialStart" > 0),
  "nextSerial" integer not null default 1 check ("nextSerial" > 0),
  timezone varchar(64) not null default 'Asia/Damascus',
  "dateFormat" varchar(32) not null default 'dd/MM/yyyy HH:mm:ss',
  "numberSystem" public.number_system not null default 'latin',
  "logoUrl" text,
  "updatedByUserId" integer references public.users(id) on delete set null,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table public.telegrams (
  id integer generated by default as identity primary key,
  "serialNumber" integer not null unique,
  "serialCode" varchar(48) not null unique,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  "createdByUserId" integer not null references public.users(id) on delete restrict,
  "creatorName" varchar(255) not null,
  "creatorEmail" varchar(320),
  "creatorBadgeId" varchar(80),
  "creatorIp" varchar(80),
  "creatorFingerprint" varchar(128),
  subject varchar(255) not null,
  recipient varchar(255) not null,
  body text not null,
  classification public.telegram_classification not null default 'normal',
  priority public.telegram_priority not null default 'normal',
  category public.telegram_category not null default 'administrative',
  status public.telegram_status not null default 'pending',
  "attachmentManifest" text,
  "gpsLatitude" varchar(40),
  "gpsLongitude" varchar(40),
  "archivedAt" timestamptz
);

create table public.audit_logs (
  id integer generated by default as identity primary key,
  "actorUserId" integer not null references public.users(id) on delete restrict,
  "actorName" varchar(255) not null,
  action varchar(80) not null,
  "entityType" varchar(80) not null,
  "entityId" varchar(80),
  metadata text,
  "createdAt" timestamptz not null default now()
);

create index telegrams_creator_idx on public.telegrams ("createdByUserId");
create index telegrams_created_at_idx on public.telegrams ("createdAt" desc);
create index telegrams_classification_idx on public.telegrams (classification);
create index audit_actor_idx on public.audit_logs ("actorUserId");
create index audit_created_at_idx on public.audit_logs ("createdAt" desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new."updatedAt" = now();
  return new;
end;
$$;

create trigger users_set_updated_at
before update on public.users
for each row execute function public.set_updated_at();

create trigger settings_set_updated_at
before update on public.department_settings
for each row execute function public.set_updated_at();

create trigger telegrams_set_updated_at
before update on public.telegrams
for each row execute function public.set_updated_at();

insert into public.department_settings ("configKey")
values ('primary')
on conflict ("configKey") do nothing;

create or replace function public.allocate_serial_number()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  allocated integer;
begin
  update public.department_settings
  set "nextSerial" = greatest("nextSerial", "serialStart") + 1
  where "configKey" = 'primary'
  returning "nextSerial" - 1 into allocated;

  if allocated is null then
    raise exception 'Primary department settings row is missing';
  end if;

  return allocated;
end;
$$;

revoke all on function public.allocate_serial_number() from public, anon, authenticated;
grant execute on function public.allocate_serial_number() to service_role;

alter table public.users enable row level security;
alter table public.department_settings enable row level security;
alter table public.telegrams enable row level security;
alter table public.audit_logs enable row level security;

revoke all on public.users from anon, authenticated;
revoke all on public.department_settings from anon, authenticated;
revoke all on public.telegrams from anon, authenticated;
revoke all on public.audit_logs from anon, authenticated;

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'telegram-files',
  'telegram-files',
  false,
  10485760,
  array[
    'image/jpeg',
    'image/png',
    'image/webp',
    'application/pdf',
    'audio/mpeg',
    'audio/wav',
    'audio/webm'
  ]
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
