import type { Request, Response } from "express";
// This module is generated by the build before Vercel bundles the function.
import { createApp } from "../dist/server/app.js";

const appPromise = createApp({ productionStatic: false });
type QueryValue = string | string[] | undefined;
type ForwardedRequest = {
  query: Record<string, QueryValue>;
  url?: string;
};

function asForwardedRequest(req: Request): ForwardedRequest {
  return req as unknown as ForwardedRequest;
}

function getForwardedPath(req: Request): string {
  const rawPath = asForwardedRequest(req).query.path;
  const pathValue = Array.isArray(rawPath) ? rawPath[0] : rawPath;

  if (typeof pathValue !== "string" || pathValue.length === 0) {
    return "/api";
  }

  const normalizedPath = pathValue.startsWith("/")
    ? pathValue
    : `/${pathValue}`;
  return normalizedPath.startsWith("/api/")
    ? normalizedPath
    : `/api${normalizedPath}`;
}

function rebuildRequestUrl(req: Request): void {
  const forwardedPath = getForwardedPath(req);
  const query = new URLSearchParams();
  const forwardedRequest = asForwardedRequest(req);

  for (const [key, value] of Object.entries(forwardedRequest.query)) {
    if (key === "path") continue;

    if (Array.isArray(value)) {
      for (const item of value) {
        if (item !== undefined) query.append(key, String(item));
      }
      continue;
    }

    if (value !== undefined) {
      query.set(key, String(value));
    }
  }

  const queryString = query.toString();
  forwardedRequest.url = queryString
    ? `${forwardedPath}?${queryString}`
    : forwardedPath;
}

export default async function handler(req: Request, res: Response) {
  rebuildRequestUrl(req);
  const app = await appPromise;
  return app(req, res);
}
